[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_title = true
opacity = 0.85
decorations = "Full"
blur = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x=10
y=10
