[colors.primary]
background = "#1c1d21"          # Was *very_dark_grey
foreground = "#848794"          # Was *light_grey
bright_foreground = "#cbcdd2"   # Was *very_light_grey

[colors.cursor]
text = "#45474f"                 # Was *dark_grey
cursor = "#e5cd52"               # Was *threepio

[colors.vi_mode_cursor]
text = "#45474f"                 # Was *dark_grey
cursor = "#e5cd52"               # Was *threepio

[colors.search.matches]
foreground = "#45474f"           # Was *dark_grey
background = "#e5cd52"           # Was *threepio

[colors.search.focused_match]
foreground = "#848794"           # Was *light_grey
background = "#eb3d54"           # Was *vader

[colors.search.bar]
background = "#848794"           # Was *light_grey
foreground = "#45474f"           # Was *dark_grey

[colors.hints.start]
foreground = "#45474f"           # Was *dark_grey
background = "#e5cd52"           # Was *threepio

[colors.hints.end]
foreground = "#e5cd52"           # Was *threepio
background = "#45474f"           # Was *dark_grey

# For 'None' values, Alacritty's TOML configuration typically accepts the string "None".
[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "#848794"                 # Was *light_grey
background = "#45474f"           # Was *dark_grey

[colors.normal]
black = "#1c1d21"                # Was *very_dark_grey
red = "#eb3d54"                  # Was *vader
green = "#78bd65"                # Was *yoda
yellow = "#e5cd52"               # Was *threepio
blue = "#4fb4d8"                 # Was *artoo
magenta = "#ef7c2a"              # Was *luke
cyan = "#4fb4d8"                 # Was *artoo
white = "#cbcdd2"                # Was *very_light_grey

[colors.bright]
black = "#1c1d21"                # Was *very_dark_grey
red = "#eb3d54"                  # Was *vader
green = "#78bd65"                # Was *yoda
yellow = "#e5cd52"               # Was *threepio
blue = "#4fb4d8"                 # Was *artoo
magenta = "#ef7c2a"              # Was *luke
cyan = "#4fb4d8"                 # Was *artoo
white = "#cbcdd2"                # Was *very_light_grey