[terminal.shell]
program = "/bin/fish"

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[window]
dynamic_title = true
opacity = 0.85
decorations = "Buttonless"
blur = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x=10
y=10
